visitor_sensors= {
                'Falkenstein-Schwellhäusl': 
                                        { 
                                            'sensor1': ['Bayerisch Eisenstein'],
                                            'sensor2': ['Bayerisch Eisenstein IN'],
                                            'sensor3': ['Bayerisch Eisenstein OUT'],
                                            'sensor4': ['Bayerisch Eisenstein Fußgänger'],
                                            'sensor5': ['Bayerisch Eisenstein Fahrräder'],
                                            'sensor6': ['Bayerisch Eisenstein Fußgänger IN'],
                                            'sensor7': ['Bayerisch Eisenstein Fußgänger OUT'],
                                            'sensor8': ['Bayerisch Eisenstein Fahrräder IN'],
                                            'sensor9': ['Bayerisch Eisenstein Fahrräder OUT'],
                                            'sensor10': ['Brechhäuslau'],
                                            'sensor11': ['Brechhäuslau IN'],
                                            'sensor12': ['Brechhäuslau OUT'],
                                            'sensor13': ['Brechhäuslau Fußgänger IN'],
                                            'sensor14': ['Brechhäuslau Fußgänger OUT'],
                                            'sensor15': ['Deffernik'],
                                            'sensor16': ['Deffernik IN'],
                                            'sensor17': ['Deffernik OUT'],
                                            'sensor18': ['Deffernik Fußgänger'],
                                            'sensor19': ['Deffernik Fahrräder'],
                                            'sensor20': ['Deffernik Fußgänger IN'],
                                            'sensor21': ['Deffernik Fußgänger OUT'],
                                            'sensor22': ['Deffernik Fahrräder IN'],
                                            'sensor23': ['Deffernik Fahrräder OUT'],
                                            'sensor24': ['Ferdinandsthal'],
                                            'sensor25': ['Ferdinandsthal IN'],
                                            'sensor26': ['Ferdinandsthal OUT'],
                                            'sensor27': ['Schillerstraße'],
                                            'sensor28': ['Schillerstraße IN'],
                                            'sensor29': ['Schillerstraße OUT'],
                                            'sensor30': ['TFG_Falkenstein_1'],
                                            'sensor31': ['TFG_Falkenstein_1 Fußgänger zum Parkplatz'],
                                            'sensor32': ['TFG_Falkenstein_1 Fußgänger zum HZW'],
                                            'sensor33': ['TFG_Falkenstein_2'],
                                            'sensor34': ['TFG_Falkenstein_2 Fußgänger In Richtung Parkplatz'],
                                            'sensor35': ['TFG_Falkenstein_2 Fußgänger In Richtung TFG'],





                                        },
                'Nationalparkzentrum Falkenstein': 
                                        {
                                            'sensor1': ['Falkenstein 1 IN', 'Falkenstein 1 OUT'],
                                            'sensor2': ['Falkenstein 2 IN', 'Falkenstein 2 OUT']
                                        },
                'Scheuereck-Schachten-Trinkwassertalsperre': 
                                        {
                                            'sensor1': ['Gsenget'],
                                            'sensor2': ['Gsenget IN'],
                                            'sensor3': ['Gsenget OUT'],
                                            'sensor4': ['Gsenget Fußgänger'],
                                            'sensor5': ['Gsenget Fahrräder'],
                                            'sensor6': ['Gsenget Fahrräder IN'],
                                            'sensor7': ['Gsenget Fahrräder OUT'],
                                            'sensor8': ['Scheuereck'],
                                            'sensor9': ['Scheuereck IN'],
                                            'sensor10': ['Scheuereck OUT'],
                                            'sensor11': ['Trinkwassertalsperre_MULTI'],
                                            'sensor12': ['Trinkwassertalsperre_MULTI IN'],
                                            'sensor13': ['Trinkwassertalsperre_MULTI OUT'],
                                            'sensor14': ['Trinkwassertalsperre_MULTI Fußgänger'],
                                            'sensor15': ['Trinkwassertalsperre_MULTI Fußgänger IN'],
                                            'sensor16': ['Trinkwassertalsperre_MULTI Fußgänger OUT'],
                                            'sensor17': ['Trinkwassertalsperre_MULTI Fahrräder'],
                                            'sensor18': ['Trinkwassertalsperre_MULTI Fahrräder IN'],    
                                            'sensor19': ['Trinkwassertalsperre_MULTI Fahrräder OUT'],


                                        },
                'Lusen-Mauth-Finsterau': 
                                        {
                                            'sensor1': ['Bucina OUT'],
                                            'sensor2' : ['Bucina_Multi'],
                                            'sensor3' : ['Bucina_Multi Fußgänger'],
                                            'sensor4' : ['Bucina_Multi Fahrräder'],
                                            'sensor5' : ['Bucina_Multi Fußgänger IN'],
                                            'sensor6' : ['Bucina_Multi Fahrräder IN'],
                                            'sensor7' : ['Bucina_Multi Fußgänger OUT'],
                                            'sensor8' : ['Bucina_Multi Fahrräder OUT'],
                                            'sensor9' : ['Felswandergebiet'],
                                            'sensor10' : ['Felswandergebiet IN'],
                                            'sensor11' : ['Felswandergebiet OUT'],
                                            'sensor12' : ['Fredenbrücke'],
                                            'sensor13' : ['Fredenbrücke Fußgänger IN'],
                                            'sensor14' : ['Fredenbrücke Fußgänger OUT'],
                                            'sensor15' : ['Sagwassersäge'],
                                            'sensor16' : ['Sagwassersäge Fußgänger IN'],
                                            'sensor17' : ['Sagwassersäge Fußgänger OUT'],
                                            'sensor18' : ['Schwarzbachbrücke'],
                                            'sensor19' : ['Schwarzbachbrücke Fußgänger IN'],
                                            'sensor20' : ['Schwarzbachbrücke Fußgänger OUT'],
                                            'sensor21' : ['Waldhausreibe'],
                                            'sensor22' : ['Waldhausreibe IN'],
                                            'sensor23' : ['Waldhausreibe OUT'],
                                            'sensor24' : ['Wistlberg'],
                                            'sensor25' : ['Wistlberg IN'],
                                            'sensor26' : ['Wistlberg Fußgänger OUT'],  
                                        },

                'Rachel-Spiegelau': 
                                        {
                                            'sensor1': ['Diensthüttenstraße'],
                                            'sensor2': ['Diensthüttenstraße Fußgänger IN'],
                                            'sensor3': ['Diensthüttenstraße Fußgänger OUT'],
                                            'sensor4': ['Gfäll'],
                                            'sensor5': ['Gfäll Fußgänger IN'],
                                            'sensor6': ['Gfäll Fußgänger OUT'],
                                            'sensor7': ['Klingenbrunner Wald'],
                                            'sensor8': ['Klingenbrunner Wald IN'],
                                            'sensor9': ['Klingenbrunner Wald OUT'],
                                            'sensor10': ['Klingenbrunner Wald Fußgänger'],
                                            'sensor11' : ['Klingenbrunner Wald Fahrräder'],
                                            'sensor12' : ['Klingenbrunner Wald Fußgänger IN'],
                                            'sensor13' : ['Klingenbrunner Wald Fußgänger OUT'],
                                            'sensor14' : ['Klingenbrunner Wald Fahrräder IN'],
                                            'sensor15' : ['Klingenbrunner Wald Fahrräder OUT'],
                                            'sensor16': ['Klosterfilz'],
                                            'sensor17': ['Klosterfilz IN'],
                                            'sensor18': ['Klosterfilz OUT'],
                                            'sensor19': ['Klosterfilz Fußgänger'],
                                            'sensor20': ['Klosterfilz Fahrräder'],
                                            'sensor21': ['Klosterfilz Fußgänger IN'],
                                            'sensor22': ['Klosterfilz Fußgänger OUT'],
                                            'sensor23': ['Klosterfilz Fahrräder IN'],
                                            'sensor24': ['Klosterfilz Fahrräder OUT'],
                                            'sensor25': ['Racheldiensthütte'],
                                            'sensor26': ['Racheldiensthütte IN'],
                                            'sensor27': ['Racheldiensthütte OUT'],
                                            'sensor28': ['Racheldiensthütte Fußgänger'],
                                            'sensor29': ['Racheldiensthütte Fahrräder'],
                                            'sensor30': ['Racheldiensthütte Fußgänger IN'],
                                            'sensor31': ['Racheldiensthütte Cyclist OUT'],
                                            'sensor32': ['Racheldiensthütte Pedestrian IN'],
                                            'sensor33': ['Racheldiensthütte Pedestrian OUT'],
                                            'sensor34': ['Waldspielgelände_1'],
                                            'sensor35': ['Waldspielgelände_1 IN'],
                                            'sensor36': ['Waldspielgelände_1 OUT'],
                                        },

                'Nationalparkzentrum Lusen': 
                                        {
                                            'sensor1': ['TFG_Lusen_1'],
                                            'sensor2': ['TFG_Lusen_1 Fußgänger Richtung TFG'],
                                            'sensor3': ['TFG_Lusen_1 Fußgänger Richtung Parkplatz'],
                                            'sensor4': ['TFG_Lusen_2'],
                                            'sensor5': ['TFG_Lusen_2 Fußgänger Richtung Vögel am Waldrand'],
                                            'sensor6': ['TFG_Lusen_2 Fußgänger Richtung Parkplatz'],
                                            'sensor7': ['TFG_Lusen_3'],
                                            'sensor8': ['TFG_Lusen_3 TFG Lusen 3 IN'],
                                            'sensor9': ['TFG_Lusen_3 TFG Lusen 3 OUT'],
                                        },
                'Time' : ['Time'],
}

visitor_centers = {
    'visitor_centers_count': {
                        'center1' :['Besuchszahlen_HEH'],
                        'center2' :['Besuchszahlen_HZW'],
                        'center3' :['Besuchszahlen_WGM'],
                        'center4' :['Parkpl_HEH_PKW'],
                        'center5' :['Parkpl_HEH_BUS'],
                        'center6' :['Parkpl_HZW_PKW'],
                        'center7' :['Parkpl_HZW_BUS'],
                        },
    'temperature_columns':
                        {
                        'property1' : ['Temperatur'],
                        'property2' : ['Niederschlagsmenge'],
                        'property3' : ['Schneehoehe'],
                        'property4' : ['GS mit'],
                        'property5' : ['GS max'],
                        'property6' :['Laubfärbung']
                           },
    'holidays' : {
                        'holiday1' :['Schulferien_Bayern'],
                        'holiday2' :['Schulferien_CZ'],
                        'holiday3' :['Feiertag_Bayern'],
                        'holiday4' :['Feiertag_CZ']

                },
    'opening_or_closed' : {
                        'center1' : ['HEH_geoeffnet'],
                        'center2' : ['HZW_geoeffnet'],
                        'center3' : ['WGM_geoeffnet'],
                        'center4' : ['Lusenschutzhaus_geoeffnet'],
                        'center5' : ['Racheldiensthuette_geoeffnet'],
                        'center6' : ['Schwellhaeusl_geoeffnet'],
                        'center7' : ['Waldschmidthaus_geoeffnet'],
                        'center8' : ['Falkensteinschutzhaus_geoeffnet']
                },
    'time': ['Datum'],
    'Day': ['Wochentag'],

}


